version: '3.4'

# Edit this file to add configuration that is specific to your instance
# Find additional documentation at https://docs.docker.com/compose/extends/

x-variables:
    - &shared-volumes
        volumes:
        # These mounts are specific to VAI
        - /varidata/research/home:/home:shared
        - /varidata/research/projects:/varidata/research/projects
        - /varidata/research/instruments:/varidata/research/instruments
        - /legacy/storage/projects:/secondary/projects

services:
    app:
        <<: *shared-volumes
    celery:
        <<: *shared-volumes

